### ISSUE TITLE
ISSUE when using MySQL 5.6 or higher version

### ISSUE THREAD

**Issue by tksarah** [irohasoft/irohaboard#1]
I found "sql_mode" is set STRICT_TRANS_TABLES in MySQL 5.6 or higher version.
In this case, we failed to install to access "http://<url>/install" for install( initializing tables for irohaboard ) . I see only "ib_users_groups" table.

Because it was checked format of "datetime".
I tried to add "SET SESSION sql_mode = '';" top of /var/www/html/Config/app.sql file, but instalation success also It seemed necessary to fix the application(  "An Internal Error" occurred after login ).

As workaround, I did down grade version of MySQL to 5.5.x.

**Comment by kokoro912** [comment]
Thank you for reporting an issue with MySQL strict mode. I could reproduce same issue on my environment and have fixed the issue. I will release a new version as soon as I have done tests for all screens.

**Comment by kokoro912** [comment]
I have fixed the issues at v0.9.18.
