### ISSUE TITLE
IIS用のweb.config設定を教えてほしい

### ISSUE THREAD

**Issue by paichi81** [irohasoft/irohaboard#10]
IIS10への導入を試してみています。
URL書き換えモジュールをインストールし、いろいろ設定を試みていますが
当方ではうまく動いておりません。

web.config設定を教えてもらえないでしょうか

## ためしていること
1. rootディレクトリのURL書き換え設定を app/webroot/index.php にしてみた
    - インストール画面まで実行できるが、/js および /css を解決できず、動作しているようにみえるが表示がくずれたままになっている
2. root, app, app/webrootそれぞれの .htaccessをインポート機能で設定
   - 404.0 error で / アクセス時に、/user/login 画面への書き換えは行われるが、index.phpが呼び出されない(?)

**Comment by kokoro912** [comment]
iroha Board が現在サポートしているのは基本的に Apache のみとなっているのですが、root ディレクトリに、添付の web.config を配置することで動作するかと思います。こちらでは Windows 10 + IIS10 で動作の確認ができました。

[web.config.zip](https://github.com/irohasoft/irohaboard/files/6242930/web.config.zip)

参考情報：CakePHP2 URLリライティング 「IIS7 (Windows ホスト) での URL 書き換え」
https://book.cakephp.org/2/ja/installation/url-rewriting.html

**Comment by paichi81** [comment]
ありがとうございます。
.htaccessがある場所ごとに読み替えでweb.configを設定していましたでしたが、appディレクトリのみにいただいたweb.configを置いたところ正しく動作できました
