### ISSUE TITLE
[FeatureRequest] 受講していない人を検索したい

### ISSUE THREAD

**Issue by paichi81** [irohasoft/irohaboard#11]
v0.10.7より個々人については残り表示されるようになったが、管理画面の学習履歴は受講した記録しか検索できない。
グループあるいはユーザで登録したコースを、まだ受講していない人を抽出できるとよい。

**Comment by irohasoft** [comment]
機能の提案ありがとうございます。未受講者の抽出については、必要性は承知しているのですが、受講登録のパターン（ユーザ数 X コース数）によっては対象者が膨大になり、また受講状況を確認するために対象の全ての学習履歴の集計を行う必要があり、システムへの負荷が極めて大きい機能となります。個別のカスタマイズによって実現している事例はございますが、現在のところ標準機能として搭載する予定はございません。
