### ISSUE TITLE
Unable to import user accounts

### ISSUE THREAD

**Issue by nmori** [irohasoft/irohaboard#5]
When importing user information, the separator between 
name and authority is not recognized correctly

If you put a full-size space after the name, the comma is recognized correctly.
If there is no space, the authority will not be read correctly and an error will occur.

The environment where the problem occurred is windows10 + XAMPP, CSV editing with Excel.

**Comment by kokoro912** [comment]
Thank you for reporting the issue. But I couldn't reproduce the issue with the latest version. It was able to import user accounts correctly. Here is the content of the CSV file I tried. There is no space between the name and the role.

ログインID,パスワード,氏名,権限,メールアドレス,備考,グループ1,グループ2,グループ3,グループ4,グループ5,グループ6,グループ7,グループ8,グループ9,グループ10,コース1,コース2,コース3,コース4,コース5,コース6,コース7,コース8,コース9,コース10,コース11,コース12,コース13,コース14,コース15,コース16,コース17,コース18,コース19,コース20
demo001,,デモ　ユーザ1,受講者,demo001@example.com,,初級クラス,,,,,,,,,,iroha Board 紹介コース,日本の歴史,,,,,,,,,,,,,,,,,,

Is it possible tell me the content of the CSV file that can reproduce the issue?

**Comment by nmori** [comment]
The problem is occurring, but seems to depend on the specific environment.

The test was conducted in two environments that were launched in the same way. 
I read a CSV file for testing, but there was no problem in one environment.

This time we have confirmed that it works correctly, so I want to close it.
If we can clarify the problem again, we will report it.

I'm sorry for causing you trouble.
