### ISSUE TITLE
教材コンテンツ閲覧ページにてテーブルレイアウトが使われている

### ISSUE THREAD

**Issue by kawadumax** [irohasoft/irohaboard#7]
WhatWGのテーブルタグの説明によると、レイアウトの目的でテーブルタグを用いるのは非推奨です。

> Tables must not be used as layout aids. Historically, some Web authors have misused tables in HTML as a way to control their page layout. This usage is non-conforming, because tools attempting to extract tabular data from such documents would obtain very confusing results. In particular, users of accessibility tools like screen readers are likely to find it very difficult to navigate pages with tables used for layout.
*There are a variety of alternatives to using HTML tables for layout, primarily using CSS positioning and the CSS table model. [[CSS]](https://html.spec.whatwg.org/multipage/references.html#refsCSS)*

![image](https://user-images.githubusercontent.com/11693767/79734394-9bdfe800-8331-11ea-93fc-ca9653583835.png)

見た目的にも、他のページはBootstrapでレイアウトされているので統一してもいいのかなと思いました。
CakePHPを書いたことがないのですが、該当するファイルは把握しましたのでもしよろしければそのうちにテンプレートファイルとcssの修正のプルリクエストをなげようかと思っています。

何か見当違いのことを書いていたなら申し訳ないですがご指摘ください。

**Comment by kokoro912** [comment]
ご指摘ありがとうございます。確かに今の時代、レイアウトに table タグは使用しないですね。
大昔のコードが放置されたままとなっておりました。コンテンツ閲覧ページについても、他のページと同じように、 Bootstrap （もしくは div のみ）でレイアウトを組み直したいと思います。
また合わせて、理解度ボタンのラベル（◎よく理解できたなど）についても、設定ファイル(Config/ib_config.php) と連動にするように実装したいと思います。

**Comment by kawadumax** [comment]
了解しました～　実装していただきありがとうございます！

**Comment by kokoro912** [comment]
修正版(v0.10.4) をリリースいたしました。
この度はありがとうございました。
