### ISSUE TITLE
コース一覧の「残り」の表示について

### ISSUE THREAD

**Issue by dekfractal** [irohasoft/irohaboard#8]
コース一覧の画面で、コンテンツの残り件数が表示されますが、「中断」で終了した場合やテストで「不合格」であった場合も残り件数から引かれます。こちらは仕様でしょうか。
Model/UsersCourse.php内のgetCourseRecordのSQLの条件次第だと思いますが、動作として少し気になりましたので、issueとして挙げさせていただきました。

<img width="1192" alt="コンテンツ一覧" src="https://user-images.githubusercontent.com/55369383/108620925-ba8f9d80-7472-11eb-89ce-cc6b66614897.png">
<img width="1194" alt="コース一覧" src="https://user-images.githubusercontent.com/55369383/108620926-bcf1f780-7472-11eb-9e0f-b2e8365d6f8d.png">

**Comment by kokoro912** [comment]
ご質問ありがとうございます。中断やテスト不合格時でも「残り」の件数から引かれる件ですが、現時点では仕様となります。getCourseRecord の SQL の受講済コンテンツの取得条件を以下のように変更する必要があります。

  WHERE r.user_id = :user_id
    AND status = 1
    AND (understanding > 0 OR is_passed = 1) #理解度を選択済、もしくはテストに合格済

その上で今後、仕様を変更するかどうか検討いたしたいと思います。

**Comment by dekfractal** [comment]
ご回答いただき、ありがとうございます。
仕様とのこと理解いたしました。
また、SQLもご教示いただきありがとうございます。

ご検討のほど、よろしくお願いいたします。

**Comment by kokoro912** [comment]
コース一覧の「残り」の計算についてですが、一度でも理解度を選択し終了した学習コンテンツ、もしくは合格したテストを「完了」と定義し、完了しているコンテンツのみを「残り」から差し引くようにいたしました。
また完了しているコンテンツが一目でわかるように、コース目次の「完了」列を追加し、完了しているコンテンツにはチェックマークを表示するようにいたしました。次の v0.10.7 にてリリース予定です。

**Comment by dekfractal** [comment]
こちらの件、ご対応いただきありがとうございます。
v0.10.7楽しみにしております。
