### ISSUE TITLE
問題文で太字装飾が使用できない

### ISSUE THREAD

**Issue by qonocy** [irohasoft/irohaboard#9]
## 発生している現象
- テストの問題文で「太字（Ctrl+B）」装飾を使用しても反映されない。
- 「コード表示」ボタンから、直接フォントウェイトを変更するスタイルを適用しても反映されない。

## 確認した環境
Windows Server 2016 + XAMPP(PHP 7.3.27) + irohaboard_v0.10.5環境で確認しました。

当方の環境によるもののみか不具合かわからなかったためIssueを立てさせて頂きました。

**Comment by kokoro912** [comment]
ご報告ありがとうございます。こちらでも類似の現象が再現できました。
スタイルシートで問題文に対して bold が適用されていたのが原因となっており、修正いたしました。
本日、本件も含めた v0.10.7 をリリース予定です。

**Comment by qonocy** [comment]
早速のご対応を頂きありがとうございます。
後ほどv0.10.7を確認させて頂きます。
